### ISSUE TITLE
Mati ya?

### ISSUE THREAD

**Issue by dhana-exe** [heirro/GoogleDrive-Link-Player#2]
Project nya sudah mati ya?
yahh sayang
kalau bisa share ke saya gan script nya semua
ntar ku host di nesia.my.id
saya pengen buat googledrive player jwplayer

**Comment by heirro** [comment]
depreciates kak, API google udah update.

**Comment by dhana-exe** [comment]
enggak ada minat update kah min?
soalnya daripada buat/beli script mending cari yg simple gini
